'use client'

import type { SortAlgorithm } from '../algorithmRegistry'
import { cocktailSortGenerator } from '../algorithms'

export const cocktailSortData: SortAlgorithm = {
  id: 'cocktailSort',
  name: 'Cocktail Shaker Sort',
  description:
    'Also known as bidirectional bubble sort, cocktail shaker sort, or shaker sort, it is a variation of Bubble Sort that sorts in both directions on each pass through the list. It improves on Bubble Sort by moving items to their correct position more quickly, particularly by helping small items at the end of the list move to the beginning faster. However, its worst-case and average-case time complexity remains O(n^2).',
  generator: cocktailSortGenerator,
  complexity: { time: { best: 'O(n)', average: 'O(n^2)', worst: 'O(n^2)' }, space: 'O(1)' },
  origin: { name: 'Variation of Bubble Sort' },
  img: '',
  pseudoCodes: {
    plaintext: [
      'procedure cocktailShakerSort(list, direction)',
      '  n = length of list',
      '  swapped = true',
      '  start = 0',
      '  end = n - 1',
      '  while swapped',
      '    swapped = false',
      '',
      '    for i = start to end - 1',
      '      if (direction == ASC and list[i] > list[i+1]) or (direction == DESC and list[i] < list[i+1]) then',
      '        swap(list[i], list[i + 1])',
      '        swapped = true',
      '      end if',
      '    end for',
      '',
      '    if not swapped then break',
      '',
      '    end = end - 1',
      '    swapped = false',
      '',
      '    for i = end - 1 down to start',
      '      if (direction == ASC and list[i] > list[i+1]) or (direction == DESC and list[i] < list[i+1]) then',
      '        swap(list[i], list[i + 1])',
      '        swapped = true',
      '      end if',
      '    end for',
      '',
      '    start = start + 1',
      '  end while',
      'end procedure',
    ],
    c: [
      '#include <stdbool.h>',
      '',
      'typedef enum { ASC, DESC } SortDirection;',
      '',
      'void swap(int *xp, int *yp) {',
      '    int temp = *xp;',
      '    *xp = *yp;',
      '    *yp = temp;',
      '}',
      '',
      'void cocktailShakerSort(int arr[], int n, SortDirection direction) {',
      '    bool swapped = true;',
      '    int start = 0;',
      '    int end = n - 1;',
      '',
      '    while (swapped) {',
      '        swapped = false;',
      '',
      '        for (int i = start; i < end; ++i) {',
      '            bool conditionMet = false;',
      '            if (direction == ASC) {',
      '                if (arr[i] > arr[i + 1]) conditionMet = true;',
      '            } else {',
      '                if (arr[i] < arr[i + 1]) conditionMet = true;',
      '            }',
      '            if (conditionMet) {',
      '                swap(&arr[i], &arr[i + 1]);',
      '                swapped = true;',
      '            }',
      '        }',
      '',
      '        if (!swapped) {',
      '            break;',
      '        }',
      '',
      '        end = end - 1;',
      '        swapped = false;',
      '',
      '        for (int i = end - 1; i >= start; --i) {',
      '            bool conditionMet = false;',
      '            if (direction == ASC) {',
      '                 if (arr[i] > arr[i + 1]) conditionMet = true;',
      '            } else { ',
      '                 if (arr[i] < arr[i + 1]) conditionMet = true;',
      '            }',
      '            if (conditionMet) {',
      '                swap(&arr[i], &arr[i + 1]);',
      '                swapped = true;',
      '            }',
      '        }',
      '',
      '        start = start + 1;',
      '    }',
      '}',
    ],
    cpp: [
      '#include <vector>',
      '#include <algorithm>',
      '',
      'enum class SortDirection { ASC, DESC };',
      '',
      'void cocktailShakerSort(std::vector<int>& arr, SortDirection direction) {',
      '    int n = arr.size();',
      '    bool swapped = true;',
      '    int start = 0;',
      '    int end = n - 1;',
      '',
      '    while (swapped) {',
      '        swapped = false;',
      '',
      '        for (int i = start; i < end; ++i) {',
      '            bool conditionMet = false;',
      '            if (direction == SortDirection::ASC) {',
      '                if (arr[i] > arr[i + 1]) conditionMet = true;',
      '            } else {',
      '                if (arr[i] < arr[i + 1]) conditionMet = true;',
      '            }',
      '            if (conditionMet) {',
      '                std::swap(arr[i], arr[i + 1]);',
      '                swapped = true;',
      '            }',
      '        }',
      '',
      '        if (!swapped) {',
      '            break;',
      '        }',
      '',
      '        end = end - 1;',
      '        swapped = false;',
      '',
      '        for (int i = end - 1; i >= start; --i) {',
      '            bool conditionMet = false;',
      '            if (direction == SortDirection::ASC) {',
      '                 if (arr[i] > arr[i + 1]) conditionMet = true;',
      '            } else { ',
      '                 if (arr[i] < arr[i + 1]) conditionMet = true;',
      '            }',
      '            if (conditionMet) {',
      '                std::swap(arr[i], arr[i + 1]);',
      '                swapped = true;',
      '            }',
      '        }',
      '',
      '        start = start + 1;',
      '    }',
      '}',
    ],
    python: [
      'def cocktail_shaker_sort(arr, direction="asc"):',
      '    n = len(arr)',
      '    swapped = True',
      '    start = 0',
      '    end = n - 1',
      '',
      '    while swapped:',
      '        swapped = False',
      '',
      '        for i in range(start, end):',
      '            condition_met = False',
      '            if direction == "asc":',
      '                if arr[i] > arr[i + 1]:',
      '                    condition_met = True',
      '            else:',
      '                if arr[i] < arr[i + 1]:',
      '                    condition_met = True',
      '',
      '            if condition_met:',
      '                arr[i], arr[i + 1] = arr[i + 1], arr[i]',
      '                swapped = True',
      '',
      '        if not swapped:',
      '            break',
      '',
      '        end -= 1',
      '        swapped = False',
      '',
      '        for i in range(end - 1, start - 1, -1):',
      '            condition_met = False',
      '            if direction == "asc":',
      '                if arr[i] > arr[i + 1]:',
      '                    condition_met = True',
      '            else:',
      '                if arr[i] < arr[i + 1]:',
      '                    condition_met = True',
      '',
      '            if condition_met:',
      '                arr[i], arr[i + 1] = arr[i + 1], arr[i]',
      '                swapped = True',
      '',
      '        start += 1',
      '',
      '    return arr',
    ],
  },
  pseudoCodeMapping: {
    0: { c: [10], cpp: [5], python: [0] },
    1: { c: [10], cpp: [6], python: [1] },
    2: { c: [11], cpp: [7], python: [2] },
    3: { c: [12], cpp: [8], python: [3] },
    4: { c: [13], cpp: [9], python: [4] },
    5: { c: [15], cpp: [11], python: [6] },
    6: { c: [16], cpp: [12], python: [7] },
    8: { c: [18], cpp: [14], python: [9] },
    9: {
      c: [20, 21, 22, 23, 24],
      cpp: [16, 17, 18, 19, 20],
      python: [11, 12, 13, 14, 15, 16, 18],
    },
    10: { c: [25], cpp: [21], python: [19] },
    11: { c: [26], cpp: [22], python: [20] },
    12: { c: [27], cpp: [23], python: [20] },
    13: { c: [28], cpp: [24], python: [20] },
    15: { c: [30, 31], cpp: [26, 27], python: [22, 23] },
    17: { c: [34], cpp: [29], python: [25] },
    18: { c: [35], cpp: [30], python: [26] },
    20: { c: [38], cpp: [33], python: [28] },
    21: {
      c: [40, 41, 42, 43, 44],
      cpp: [35, 36, 37, 38, 39],
      python: [30, 31, 32, 33, 34, 35, 37],
    },
    22: { c: [45], cpp: [40], python: [38] },
    23: { c: [46], cpp: [41], python: [39] },
    24: { c: [47], cpp: [42], python: [39] },
    27: { c: [50], cpp: [45], python: [42] },
    28: { c: [51], cpp: [46], python: [44] },
    29: { c: [52], cpp: [47], python: [44] },
  },
  hasAdvancedAuxiliaryVisuals: false,
}
