import type { SortAlgorithm } from '../algorithmRegistry'

const rawPlaintextPseudoCode = [
  'procedure insertionSort(list, direction)',
  '  n = length of list',
  '  if n <= 1 then return list',
  '',
  '  for i = 1 to n - 1',
  '    key = list[i]',
  '    j = i - 1',
  '    while j >= 0 and ((direction == ASC and list[j] > key) or (direction == DESC and list[j] < key))',
  '      list[j + 1] = list[j]',
  '      j = j - 1',
  '    end while',
  '    list[j + 1] = key',
  '  end for',
  '  return list',
  'end procedure',
]

export const insertionSortData: SortAlgorithm = {
  id: 'insertionSort',
  name: 'Insertion Sort',
  description:
    "Much like sorting a hand of playing cards, Insertion Sort builds the final sorted array one item at a time. It takes each element from the input and inserts it into the correct position within the already sorted portion of the array. It\'s simple to implement and efficient for small datasets or nearly sorted data, as it only requires shifting elements to make space for the new insertion.",
  complexity: { time: { best: 'O(n)', average: 'O(n^2)', worst: 'O(n^2)' }, space: 'O(1)' },
  origin: { name: 'Fundamental/Early' },
  img: '',
  pseudoCode: rawPlaintextPseudoCode,
  languageExamples: {
    c: [
      '#include <stdbool.h>',
      '',
      'void insertionSort(int arr[], int n, bool ascending) {',
      '    if (n <= 1) return;',
      '    int i, key, j;',
      '    for (i = 1; i < n; i++) {',
      '        key = arr[i];',
      '        j = i - 1;',
      '        ',
      '        if (ascending) {',
      '            while (j >= 0 && arr[j] > key) {',
      '                arr[j + 1] = arr[j];',
      '                j = j - 1;',
      '            }',
      '        } else {',
      '            while (j >= 0 && arr[j] < key) {',
      '                arr[j + 1] = arr[j];',
      '                j = j - 1;',
      '            }',
      '        }',
      '        arr[j + 1] = key;',
      '    }',
      '}',
    ],
    cpp: [
      '#include <vector>',
      // '#include <stdbool.h>', // bool is a keyword in C++
      '',
      'template <typename T>',
      'void insertionSort(std::vector<T>& arr, bool ascending) {',
      '    int n = arr.size();',
      '    if (n <= 1) return;',
      '    for (int i = 1; i < n; ++i) {',
      '        T key = arr[i];',
      '        int j = i - 1;',
      '',
      '        if (ascending) {',
      '            while (j >= 0 && arr[j] > key) {',
      '                arr[j + 1] = arr[j];',
      '                --j;',
      '            }',
      '        } else {',
      '            while (j >= 0 && arr[j] < key) {',
      '                arr[j + 1] = arr[j];',
      '                --j;',
      '            }',
      '        }',
      '        arr[j + 1] = key;',
      '    }',
      '}',
    ],
    python: [
      'def insertionSort(arr, ascending=True):',
      '    n = len(arr)',
      '    if n <= 1:',
      '        return arr',
      '        ',
      '    for i in range(1, n):',
      '        key = arr[i]',
      '        j = i - 1',
      '        ',
      '        if ascending:',
      '            while j >= 0 and arr[j] > key:',
      '                arr[j + 1] = arr[j]',
      '                j -= 1',
      '        else:',
      '            while j >= 0 and arr[j] < key:',
      '                arr[j + 1] = arr[j]',
      '                j -= 1',
      '        arr[j + 1] = key',
      '    return arr',
    ],
  },
  pseudoCodeMapping: {
    0: { c: [3], cpp: [5], python: [1] },
    1: { c: [3], cpp: [6], python: [2] },
    2: { c: [4], cpp: [7], python: [3, 4] },
    4: { c: [6], cpp: [8], python: [6] },
    5: { c: [7], cpp: [9], python: [7] },
    6: { c: [8], cpp: [10], python: [8] },
    7: { c: [10, 16], cpp: [12, 18], python: [10, 18] },
    8: { c: [17], cpp: [19], python: [21] },
    9: { c: [18], cpp: [20], python: [22] },
    10: { c: [23], cpp: [25], python: [19] },
    11: { c: [24], cpp: [26], python: [24] },
    12: { c: [25], cpp: [27], python: [25] },
    13: { c: [25], cpp: [27], python: [26] },
    14: { c: [25], cpp: [27], python: [26] },
  },
  performancePaths: {
    best: [0, 1, 2, 4, 5, 6, 7, 10, 11, 12, 13, 14],
    worst: [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    average: [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
  },
}
